[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 200
verbosity = 2

[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000 }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC_URL}"
base = "${BASE_RPC_URL}"
sova = "${SOVA_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }
sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }